# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1179d8f610c15ff4d5831848aba684c2b6b8101d995953aa736cc8a5cd54521553656d9284b11df1dc266405bc94eb38100db4d88e8fb8f43ea5a748393b9181

test:
  secret_key_base: 56b4c4059451ea7fa6017e9926ead41fa53a4a977a1f1d1aea702118103c6eac440395dcf66c947a6f140847fc98bb73cb4167d575a77f24e350bfc4be84c0ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
